---
title: "20240801-Fig1"
author: "Zhenxiong Jiang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
```

To plot the quantitative PCR result between S.elongatus PCC7942 and mSe0:
In put data:
```{r}
nitrogen <- c(rep("Nitrate",6),rep("Ammonium",6))
strain <- c(rep("PCC7942 WT",3),rep("mSe0",3),rep("PCC7942 WT",3),rep("mSe0",3))
rq <- c(0.2480,0.4500,0.3370,1.0850,1.2120,1.3630,2.5200,2.4800,3.0800,0.0314,0.0439,0.2210)
dat <- tibble(Strain=strain,
              nitrogen.source=nitrogen,
              relative.quant = rq)
dat.stat <- dat %>% group_by(Strain,nitrogen.source) %>% summarise(rq.mean=mean(relative.quant),rq.std=std(relative.quant))
```
```{r}
t.test(dat[(dat$Strain=="PCC7942 WT")&(dat$nitrogen.source=="Nitrate"),]$relative.quant,dat[(dat$Strain=="mSe0")&(dat$nitrogen.source=="Ammonium"),]$relative.quant)
t.test(dat[(dat$Strain=="PCC7942 WT")&(dat$nitrogen.source=="Nitrate"),]$relative.quant,dat[(dat$Strain=="mSe0")&(dat$nitrogen.source=="Nitrate"),]$relative.quant)
t.test(dat[(dat$Strain=="PCC7942 WT")&(dat$nitrogen.source=="Ammonium"),]$relative.quant,dat[(dat$Strain=="mSe0")&(dat$nitrogen.source=="Ammonium"),]$relative.quant)
t.test(dat[(dat$Strain=="mSe0")&(dat$nitrogen.source=="Nitrate"),]$relative.quant,dat[(dat$Strain=="mSe0")&(dat$nitrogen.source=="Ammonium"),]$relative.quant)
```

Plotting:
```{r}
bottom <- 3.2

qPCR.plot <- 
ggplot()+
  geom_col(dat.stat,mapping=aes(x=nitrogen.source,y=rq.mean,fill=Strain),position = "dodge",width=0.5,color="grey0")+
  geom_errorbar(dat.stat,mapping=aes(x=nitrogen.source,ymin=rq.mean-rq.std, ymax=rq.mean+rq.std,fill=Strain),position = position_dodge(width = 0.5),width=0.2)+
  scale_fill_manual(values=c("#AFAFA9","grey30"),
                    labels=c("Hypermutator mSe0",expression(italic("S. elongatus")*" PCC 7942")))+
  geom_point(data=dat,mapping = aes(x=nitrogen.source,y=relative.quant,color=Strain),
             size=0.8,
             position=position_jitterdodge(jitter.width = 0.2,dodge.width=0.5),show_guide=FALSE)+
  scale_color_manual(values=c("grey0","grey0"))+
  theme_classic()+
  ylab(expression("Relative quantity " * italic("mutS/rnpB")))+
  xlab("")+
  theme(plot.margin = unit(c(0,0,0,0),"cm"),
        legend.text.align = 0,
        legend.position = c(0.7,0.6),
        legend.text=element_text(size=16/ .pt),
        legend.title = element_text(size=16/ .pt),
        legend.key.size = unit(0.4,"line"),
        legend.background = element_rect(fill = "transparent"),
        axis.text=element_text(size=24/ .pt),
        axis.title=element_text(size=24/ .pt))+
  geom_segment(aes(x=1.875,xend=2.125,y=bottom+0.1,yend=bottom+0.1))+
  geom_segment(aes(x=1.875,xend=1.875,y=bottom+0.1,yend=bottom))+
  geom_segment(aes(x=2.125,xend=2.125,y=bottom+0.1,yend=bottom))+
  annotate("text", x = 2, y = bottom+0.15, 
           label = "**",
           size = 16 / .pt, color = "#22292F")+
  geom_segment(aes(x=0.875,xend=1.875,y=bottom+0.4,yend=bottom+0.4))+
  geom_segment(aes(x=0.875,xend=0.875,y=bottom+0.4,yend=bottom+0.3))+
  geom_segment(aes(x=1.875,xend=1.875,y=bottom+0.4,yend=bottom+0.3))+
  annotate("text", x = 1.375, y = bottom+0.45, 
           label = "***",
           size = 16 / .pt, color = "#22292F")+
  
  
  geom_segment(aes(x=0.875,xend=1.125,y=bottom+0.1,yend=bottom+0.1))+
  geom_segment(aes(x=0.875,xend=0.875,y=bottom+0.1,yend=bottom))+
  geom_segment(aes(x=1.125,xend=1.125,y=bottom+0.1,yend=bottom))+
  annotate("text", x = 1, y = bottom+0.15, 
           label = "**",
           size = 16 / .pt, color = "#22292F")+
  
  scale_y_continuous(expand = c(0,0),limits=c(-0.01,4.2))
  
ggsave(filename = file.path("./image","20250415-Fig1c.pdf"),plot = qPCR.plot, device = "pdf", width = 8.5, height = 5, units = "cm")
  

```



